mv: cannot stat 'job_logs/train.err': No such file or directory
Starting training on cx3-20-6.cx3.hpc.ic.ac.uk at Sun 20 Apr 18:12:42 BST 2025
Using config: configs/batch_6/config_zoom_m43.json
Traceback (most recent call last):
  File "/rds/general/user/psp20/home/Brain-Network/source/simple_cnn.py", line 627, in <module>
    main()
  File "/rds/general/user/psp20/home/Brain-Network/source/simple_cnn.py", line 576, in main
    best_loss_res = test_model(
                    ^^^^^^^^^^^
  File "/rds/general/user/psp20/home/Brain-Network/source/simple_cnn.py", line 317, in test_model
    adv_images = attacker(images, labels)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/miniforge3/envs/brain-network-env/lib/python3.11/site-packages/torchattacks/attack.py", line 511, in __call__
    adv_inputs = self.forward(inputs, labels, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/miniforge3/envs/brain-network-env/lib/python3.11/site-packages/torchattacks/attacks/pgd.py", line 63, in forward
    outputs = self.get_logits(adv_images)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/miniforge3/envs/brain-network-env/lib/python3.11/site-packages/torchattacks/attack.py", line 79, in get_logits
    logits = self.model(inputs)
             ^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/Brain-Network/source/models.py", line 258, in forward
    tokens = block(tokens, gamma)
             ^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/Brain-Network/source/zoom_att.py", line 79, in forward
    x = x + self.attn(self.norm1(x), gamma)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/Brain-Network/source/zoom_att.py", line 53, in forward
    qkv = self.qkv(x).reshape(B, N, 3, H, D // H).permute(2, 0, 3, 1, 4)
          ^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/psp20/home/.local/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 44.42 GiB of which 2.12 MiB is free. Including non-PyTorch memory, this process has 44.41 GiB memory in use. Of the allocated memory 42.09 GiB is allocated by PyTorch, and 1.81 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Finished at Sun 20 Apr 18:20:31 BST 2025

====================================
CPU Time used: 00:12:42
CPU Percent: 231%
Memory usage: 1611780kb
Approx Power usage: 0.0024000000000000002
Walltime usage: 00:07:59

====================================
